### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by KingWang569** [aigc3d/LHM-plusplus#4]
It's a very interesting work !
but I encountered a memory overflow issue while running the inference (my graphics card has 16GB of RAM).
The actual 8GB of VRAM mentioned on the GitHub homepage is different. How can I resolve this issue?

~/LHM-plusplus$ python ./app.py --model_name LHMPPS-700M
huggingface_hub imported successfully.
modelscope imported successfully.

--- Querying model: LHMPPS-700M ---
Step 1: Checking local ModelScope cache...
Checking cache for ModelScope model: Damo_XR_Lab/LHMPPS-700M
Found local ModelScope model at: /home/king/LHM-plusplus/pretrained_models/Damo_XR_Lab/LHMPPS-700M
Success: Found in local ModelScope cache: /home/king/LHM-plusplus/pretrained_models/Damo_XR_Lab/LHMPPS-700M
/home/king/LHM-plusplus/core/models/encoders/dinov2/layers/swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
/home/king/LHM-plusplus/core/models/encoders/dinov2/layers/attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
/home/king/LHM-plusplus/core/models/encoders/dinov2/layers/block.py:39: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")
[RANK 0] ======== Freezing Dinov2Wrapper ========
==========skip_decoder:True
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Unable Flash Attention
Using FLAME expression
<All keys matched successfully>
Loading weights from local directory
[896]
Loading model...
/home/king/LHM-plusplus/./engine/pose_estimation/blocks/../dinov2/dinov2/layers/swiglu_ffn.py:43: UserWarning: xFormers is available (SwiGLU)
  warnings.warn("xFormers is available (SwiGLU)")
/home/king/LHM-plusplus/./engine/pose_estimation/blocks/../dinov2/dinov2/layers/attention.py:27: UserWarning: xFormers is available (Attention)
  warnings.warn("xFormers is available (Attention)")
/home/king/LHM-plusplus/./engine/pose_estimation/blocks/../dinov2/dinov2/layers/block.py:33: UserWarning: xFormers is available (Block)
  warnings.warn("xFormers is available (Block)")
person center is head
Model loaded
/home/king/LHM-plusplus/./app.py:223: DeprecationWarning: The 'theme' parameter in the Blocks constructor will be removed in Gradio 6.0. You will need to pass 'theme' to Blocks.launch() instead.
  with gr.Blocks(
/home/king/LHM-plusplus/./app.py:223: DeprecationWarning: The 'css' parameter in the Blocks constructor will be removed in Gradio 6.0. You will need to pass 'css' to Blocks.launch() instead.
  with gr.Blocks(
* Running on local URL:  http://0.0.0.0:7860
* To create a public link, set `share=True` in `launch()`.
/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
staring testing
Traceback (most recent call last):
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/gradio/queueing.py", line 759, in process_events
    response = await route_utils.call_process_api(
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/gradio/route_utils.py", line 354, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/gradio/blocks.py", line 2191, in process_api
    result = await self.call_function(
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/gradio/blocks.py", line 1698, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/anyio/to_thread.py", line 63, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2518, in run_sync_in_worker_thread
    return await future
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1002, in run
    result = context.run(func, *args)
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/gradio/utils.py", line 915, in wrapper
    response = f(*args, **kwargs)
  File "/home/king/LHM-plusplus/./app.py", line 161, in core_fn
    rgbs = inference_results(
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/king/LHM-plusplus/scripts/inference/app_inference.py", line 120, in inference_results
    model_outputs = model.infer_single_view(
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/king/LHM-plusplus/core/models/modeling_humana4o_lrm.py", line 1016, in infer_single_view
    latent_points, image_feats, motion_emb, pos_emb = self.forward_latent_points(
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/home/king/LHM-plusplus/core/models/modeling_humana4o_lrm.py", line 735, in forward_latent_points
    results = self.forward_transformer(
  File "/home/king/LHM-plusplus/core/models/modeling_humana4o_lrm.py", line 644, in forward_transformer
    transformer_results = self.transformer(
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/king/LHM-plusplus/core/models/transformer_block/efficient_pi_transformer_dense.py", line 155, in forward
    query_feats, img_feats, update_motion_emb, pos = self._forward_per_batch(
  File "/home/king/LHM-plusplus/core/models/transformer_block/efficient_pi_transformer_dense.py", line 442, in _forward_per_batch
    query_points = self.point_backbone.dec[depth_i](query_points)
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/king/LHM-plusplus/core/models/encoders/sonata/module.py", line 87, in forward
    input = module(input)
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/king/LHM-plusplus/core/models/encoders/sonata/model.py", line 387, in forward
    point = self.drop_path(self.ls1(self.attn(point)))
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/king/LHM-plusplus/core/models/encoders/sonata/model.py", line 249, in forward
    attn = self.softmax(attn)
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/activation.py", line 1545, in forward
    return F.softmax(input, self.dim, _stacklevel=5)
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/functional.py", line 1885, in softmax
    ret = input.softmax(dim)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 6.00 GiB. GPU 
staring testing
Traceback (most recent call last):
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/gradio/queueing.py", line 759, in process_events
    response = await route_utils.call_process_api(
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/gradio/route_utils.py", line 354, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/gradio/blocks.py", line 2191, in process_api
    result = await self.call_function(
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/gradio/blocks.py", line 1698, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/anyio/to_thread.py", line 63, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2518, in run_sync_in_worker_thread
    return await future
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1002, in run
    result = context.run(func, *args)
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/gradio/utils.py", line 915, in wrapper
    response = f(*args, **kwargs)
  File "/home/king/LHM-plusplus/./app.py", line 161, in core_fn
    rgbs = inference_results(
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/king/LHM-plusplus/scripts/inference/app_inference.py", line 120, in inference_results
    model_outputs = model.infer_single_view(
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/king/LHM-plusplus/core/models/modeling_humana4o_lrm.py", line 1016, in infer_single_view
    latent_points, image_feats, motion_emb, pos_emb = self.forward_latent_points(
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "/home/king/LHM-plusplus/core/models/modeling_humana4o_lrm.py", line 735, in forward_latent_points
    results = self.forward_transformer(
  File "/home/king/LHM-plusplus/core/models/modeling_humana4o_lrm.py", line 644, in forward_transformer
    transformer_results = self.transformer(
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/king/LHM-plusplus/core/models/transformer_block/efficient_pi_transformer_dense.py", line 155, in forward
    query_feats, img_feats, update_motion_emb, pos = self._forward_per_batch(
  File "/home/king/LHM-plusplus/core/models/transformer_block/efficient_pi_transformer_dense.py", line 376, in _forward_per_batch
    query_points = self.point_backbone.enc[0](query_points)
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/king/LHM-plusplus/core/models/encoders/sonata/module.py", line 87, in forward
    input = module(input)
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/king/LHM-plusplus/core/models/encoders/sonata/model.py", line 387, in forward
    point = self.drop_path(self.ls1(self.attn(point)))
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/king/LHM-plusplus/core/models/encoders/sonata/model.py", line 249, in forward
    attn = self.softmax(attn)
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/modules/activation.py", line 1545, in forward
    return F.softmax(input, self.dim, _stacklevel=5)
  File "/home/king/.conda/envs/lhmpp/lib/python3.10/site-packages/torch/nn/functional.py", line 1885, in softmax
    ret = input.softmax(dim)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.50 GiB. GPU

**Comment by lingtengqiu** [comment]
What GPU device and memory are you using? For successfully running LHMPP and producing the final animation rendering results, you utilize the memory of your GPU at least 8GB. I saw you use 16GB RAM.  Does this refer to GPU VRAM? If yes, could you provide your runtime logs?, or the monitoring outputs about GPU memory during running the app.

**Comment by lingtengqiu** [comment]
Maybe you can try the following codes to monitor the gpu usage during the Gradio exection. 
```python
#!/usr/bin/env python3
"""
用法：
  python scripts/gpu_peak_monitor.py              # default, 1 hours for monitoring your memory of GPU usage.
  python scripts/gpu_peak_monitor.py -d 0         # keeping monitoring your gpu usage until pressing ctrl+C
  python scripts/gpu_peak_monitor.py -d 1800 -i 0.5
  python scripts/gpu_peak_monitor.py --compact -d 0 # Monitoring your gpu in the terminal.
"""
from __future__ import annotations

import argparse
import csv
import io
import subprocess
import sys
import time
from dataclasses import dataclass, field
from typing import List, Tuple


@dataclass
class GpuPeakState:
    index: int
    name: str
    peak_util: int = 0
    peak_mem_mib: int = 0
    mem_total_mib: int = 0


@dataclass
class MonitorState:
    gpus: List[GpuPeakState] = field(default_factory=list)
    peak_util_any: int = 0
    """Global peak utilization across all GPUs and all sampling moments."""
    peak_mem_any_mib: int = 0
    """Global peak of 'used memory' for a single card (the max usage of any single GPU at any given moment)."""
    global_peak_sum_mib: int = 0
    """Global peak of the sum of 'used memory' across all GPUs (more meaningful for multi-GPU parallel loads)."""


def query_gpus() -> List[Tuple[int, str, int, int, int]]:
    """
    Returns [(index, name, util_pct, used_mib, total_mib), ...]
    """
    cmd = [
        "nvidia-smi",
        "--query-gpu=index,name,utilization.gpu,memory.used,memory.total",
        "--format=csv,noheader,nounits",
    ]
    out = subprocess.check_output(cmd, text=True, stderr=subprocess.STDOUT)
    rows: List[Tuple[int, str, int, int, int]] = []
    for line in out.strip().splitlines():
        line = line.strip()
        if not line:
            continue
        r = next(csv.reader(io.StringIO(line)))
        if len(r) < 5:
            continue
        idx = int(r[0].strip())
        name = r[1].strip()
        util = int(r[2].strip().replace(" %", "").replace("%", ""))
        mem_used = int(r[3].strip().replace(" MiB", "").replace("MiB", ""))
        mem_total = int(r[4].strip().replace(" MiB", "").replace("MiB", ""))
        rows.append((idx, name, util, mem_used, mem_total))
    return rows


def merge_peaks(state: MonitorState, samples: List[Tuple[int, str, int, int, int]]) -> None:
    """Update per-GPU peaks and global peaks using the current sample."""
    sum_used = sum(s[3] for s in samples)
    state.global_peak_sum_mib = max(state.global_peak_sum_mib, sum_used)

    max_used_this_tick = max((s[3] for s in samples), default=0)
    state.peak_mem_any_mib = max(state.peak_mem_any_mib, max_used_this_tick)

    if not state.gpus:
        for idx, name, util, used, total in samples:
            state.gpus.append(
                GpuPeakState(
                    index=idx,
                    name=name,
                    peak_util=util,
                    peak_mem_mib=used,
                    mem_total_mib=total,
                )
            )
            state.peak_util_any = max(state.peak_util_any, util)
        return

    by_idx = {g.index: g for g in state.gpus}
    for idx, name, util, used, total in samples:
        g = by_idx.get(idx)
        if g is None:
            state.gpus.append(
                GpuPeakState(
                    index=idx,
                    name=name,
                    peak_util=util,
                    peak_mem_mib=used,
                    mem_total_mib=total,
                )
            )
            g = state.gpus[-1]
            by_idx[idx] = g
        g.peak_util = max(g.peak_util, util)
        g.peak_mem_mib = max(g.peak_mem_mib, used)
        if total > 0:
            g.mem_total_mib = total
        state.peak_util_any = max(state.peak_util_any, util)


def format_duration(sec: float) -> str:
    m, s = divmod(int(sec), 60)
    h, m = divmod(m, 60)
    if h:
        return f"{h}h {m}m {s}s"
    if m:
        return f"{m}m {s}s"
    return f"{s}s"


def main() -> int:
    p = argparse.ArgumentParser(
        description="Real-time GPU memory/utilization monitoring, recording peaks (max single-card usage and multi-card sum)."
    )
    p.add_argument(
        "-d",
        "--duration",
        type=float,
        default=3600.0,
        help="Total monitoring duration (seconds). 0 means run indefinitely until Ctrl+C. Default: 3600",
    )
    p.add_argument(
        "-i",
        "--interval",
        type=float,
        default=1.0,
        help="Sampling interval (seconds), default: 1",
    )
    p.add_argument(
        "-q",
        "--quiet",
        action="store_true",
        help="Do not print each sample; only output summary at the end",
    )
    p.add_argument(
        "--compact",
        action="store_true",
        help="Single-line \\r refresh (current used MiB per card + global peaks)",
    )
    args = p.parse_args()

    if args.duration < 0:
        print("Duration cannot be negative (0 means infinite)", file=sys.stderr)
        return 2
    if args.interval <= 0:
        print("Interval must be positive", file=sys.stderr)
        return 2

    start = time.monotonic()
    end = start + args.duration if args.duration > 0 else None
    state = MonitorState()
    sample_n = 0

    try:
        while True:
            if end is not None and time.monotonic() >= end:
                break
            try:
                samples = query_gpus()
            except (subprocess.CalledProcessError, FileNotFoundError) as e:
                print(f"nvidia-smi call failed: {e}", file=sys.stderr)
                return 1
            if not samples:
                print("No GPUs detected, exiting", file=sys.stderr)
                return 1
            merge_peaks(state, samples)
            sample_n += 1
            if not args.quiet:
                elapsed = time.monotonic() - start
                by_idx = {s[0]: s for s in samples}
                if args.compact:
                    cur_parts = [f"G{i}:{by_idx[i][3]}MiB" for i in sorted(by_idx)]
                    line = (
                        f"[{elapsed:7.1f}s] "
                        + " ".join(cur_parts)
                        + f" | SingleCardPeak:{state.peak_mem_any_mib}MiB"
                        f" SumPeak:{state.global_peak_sum_mib}MiB"
                    )
                    pad = max(0, 120 - len(line))
                    print("\r" + line + " " * pad, end="", flush=True)
                else:
                    print(f"--- t={elapsed:7.1f}s ---", flush=True)
                    for g in sorted(state.gpus, key=lambda x: x.index):
                        cur = by_idx.get(g.index)
                        u_cur = cur[3] if cur else 0
                        util_cur = cur[2] if cur else 0
                        total = g.mem_total_mib
                        pct_peak = (100.0 * g.peak_mem_mib / total) if total else 0.0
                        pct_cur = (100.0 * u_cur / total) if total else 0.0
                        print(
                            f"  GPU{g.index} ({g.name}): "
                            f"Used {u_cur} MiB ({pct_cur:.1f}%)  "
                            f"util {util_cur}%  |  "
                            f"MemPeak {g.peak_mem_mib} MiB ({pct_peak:.1f}% of {total} MiB)",
                            flush=True,
                        )
                    print(
                        f"  Global: util peak {state.peak_util_any}%  |  "
                        f"SingleCard MemPeak (max of any card) {state.peak_mem_any_mib} MiB  |  "
                        f"MultiCard SumPeak Σ {state.global_peak_sum_mib} MiB",
                        flush=True,
                    )
            if end is not None:
                remaining = end - time.monotonic()
                if remaining <= 0:
                    break
                sleep_t = min(args.interval, remaining)
            else:
                sleep_t = args.interval
            time.sleep(sleep_t)
    except KeyboardInterrupt:
        if args.compact:
            print()
        print("\nInterrupted, outputting current accumulated peaks:", flush=True)

    elapsed = time.monotonic() - start
    print()
    print("========== GPU Peak Summary ==========")
    print(f"Actual Duration: {format_duration(elapsed)}  Samples: {sample_n}")
    print(
        f"Global — Utilization Peak: {state.peak_util_any}%  |  "
        f"SingleCard MemPeak (max used by any single card across all samples): {state.peak_mem_any_mib} MiB  |  "
        f"MultiCard SumPeak: {state.global_peak_sum_mib} MiB"
    )
    print("Per-GPU Memory/Utilization Peaks:")
    for g in sorted(state.gpus, key=lambda x: x.index):
        total = g.mem_total_mib
        pct = (100.0 * g.peak_mem_mib / total) if total else 0.0
        print(
            f"  GPU {g.index} ({g.name}): "
            f"util peak {g.peak_util}%  |  "
            f"mem peak {g.peak_mem_mib} / {total} MiB ({pct:.1f}%)"
        )
    print("==================================")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())



```

**Comment by KingWang569** [comment]
Thank you so much for your help. The actual reason was that Flash Attention was not installed correctly. After compiling and installing it, the problem disappeared.
